### ISSUE TITLE
I can not create the ticket

### ISSUE THREAD

**Issue by WassapMannn** [fahidjavid/simple-support-system#2]
Hi there. 
I see that you stop updating the plugin. Thank you for this wonderful tool, it handles alot. 
I am not sure if tou care alot but I would like to state an issue. I set it up as you show in READ ME but some how I can not create a ticket as it says **Please enter an item purchase code on Your Purchases page, before you submit a ticket.** Woocommerce does not create purchase code either...

Thank you.

**Comment by fahidjavid** [comment]
Hi!

That plugin works for only https://envato.com/ market places' products. Purchase code will be used only of the products users buy from Envato marketplaces.

Thanks,

Fahid
